# Docker Compose para desarrollo y pruebas
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./out:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

# Para usar:
# 1. docker-compose up --build
# 2. Abrir http://localhost:8080
